// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9x2Mxyr5KfyNKaRrli2gD6BPbk0SdnWE',
    appId: '1:42362165294:web:d179e02ef7212d9cb3a7bf',
    messagingSenderId: '42362165294',
    projectId: 'flutter-cookbook-7d4af',
    authDomain: 'flutter-cookbook-7d4af.firebaseapp.com',
    storageBucket: 'flutter-cookbook-7d4af.appspot.com',
    measurementId: 'G-M2SZYTDZ3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGQ6fN7ajqU3f9uEM2FsEbubkDkn1jFKY',
    appId: '1:42362165294:android:9cdcf8c013dbbe7bb3a7bf',
    messagingSenderId: '42362165294',
    projectId: 'flutter-cookbook-7d4af',
    storageBucket: 'flutter-cookbook-7d4af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF0d8uhWvXcs2Z32T8I9CVvsJgfeu-KWM',
    appId: '1:42362165294:ios:4dc47200a0dc3a49b3a7bf',
    messagingSenderId: '42362165294',
    projectId: 'flutter-cookbook-7d4af',
    storageBucket: 'flutter-cookbook-7d4af.appspot.com',
    iosClientId: '42362165294-rb4737thpd7f474373qo8u1gb0g2a8le.apps.googleusercontent.com',
    iosBundleId: 'com.sharon.atim.firebase',
  );
}
